// Compatibility loader for launchers that still reference this file. The
// production runner uses a package-root-specific copy generated by
// plugin-security.mjs. Keep this deny-list fail-closed.
const blockedModules = new Set(['http', 'https', 'http2', 'net', 'tls', 'dns', 'dgram', 'cluster', 'fs', 'child_process', 'worker_threads', 'module', 'vm', 'inspector', 'wasi']);

export async function resolve(specifier, context, nextResolve) {
  const name = String(specifier).replace(/^node:/, '').split('/')[0];
  if (blockedModules.has(name)) throw new Error(`Plugin import blocked: ${name}.`);
  return nextResolve(specifier, context);
}
